# Generated by Django 2.0.5 on 2018-05-06 14:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardno', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Card No')),
                ('ccv', models.IntegerField(verbose_name='CCV')),
                ('expdate', models.DateTimeField(verbose_name='Expiration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Masa',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Masa No')),
            ],
        ),
        migrations.CreateModel(
            name='MasaSecimi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerestaurant.Masa')),
            ],
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50, verbose_name='Isim')),
                ('addr', models.CharField(max_length=250, verbose_name='Adres')),
                ('telno', models.IntegerField(unique=True, verbose_name='Telefon Numarasi')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rezervasyon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Rezervasyon Tarihi')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerestaurant.Musteri')),
            ],
        ),
        migrations.CreateModel(
            name='SiparisHavuzu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True, verbose_name='Siparis Tarihi')),
                ('ispayed', models.BooleanField(default=False, verbose_name='Odendi')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerestaurant.Musteri')),
            ],
        ),
        migrations.CreateModel(
            name='Yemek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edibletype', models.IntegerField(choices=[(0, 'Ana Yemek'), (1, 'Ara Sicak'), (2, 'Tatli'), (3, 'Icecek')], verbose_name='Tur')),
                ('name', models.CharField(max_length=50, verbose_name='Yemek Ismi')),
                ('price', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ucret')),
                ('preptime', models.IntegerField(verbose_name='Hazirlanma Suresi (dk)')),
            ],
        ),
        migrations.CreateModel(
            name='YemekSiparisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerestaurant.SiparisHavuzu')),
                ('yemek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerestaurant.Yemek')),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(verbose_name='Siparis Tarihi')),
                ('comment', models.CharField(max_length=500, verbose_name='Yorum')),
                ('star', models.IntegerField(verbose_name='Yildiz')),
            ],
        ),
        migrations.AddField(
            model_name='masasecimi',
            name='rezervasyon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerestaurant.Rezervasyon'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerestaurant.Musteri'),
        ),
    ]
