# Generated by Django 2.0.5 on 2018-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='puan',
            field=models.IntegerField(default=5, verbose_name='Sistem Puani'),
        ),
    ]
