# Generated by Django 2.0.5 on 2018-05-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerestaurant', '0002_musteri_puan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='owner',
        ),
        migrations.AddField(
            model_name='yemeksiparisi',
            name='onay',
            field=models.BooleanField(default=0, verbose_name='Onay'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
